[package]
name = "cargo-watch-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
serde_json = "1.0"
assert_cli = "0.6.3"
tempfile = "3.14.0"
