version: "3.9"
services:
  app:
    build: .
    container_name: "cargo-watch-example"
    volumes:
      - .:/app
    command: sh -c "cargo watch -w src --poll -x run"
    stdin_open: true   # Keeps stdin open for interaction
    tty: true          # Allocates a pseudo-TTY
